### ISSUE TITLE
Delete stale branches. Delete normalize and DS_Fix from open-source-labs/obsidian 

### ISSUE THREAD

**Issue by 8D-k** [open-source-labs/obsidian#65]
If these branches do not have an active purpose, let's delete them
Delete normalize and DS_Fix.
https://github.com/open-source-labs/obsidian/tree/normalize 
https://github.com/open-source-labs/obsidian/tree/DS_Fix
@TravisFrankMTG Are these still in use for release processes?

[expected]
only keep active branches for development

[actual]
normalize
Updated 14 months ago by TravisFrankMTG
DS_Fix
Updated 14 months ago by TravisFrankMTG

**Comment by travismfrank** [comment]
Agreed, I'll delete the branches.  Thanks for calling out!

**Comment by 8D-k** [comment]
Thank you for the quick resolution! @TravisFrankMTG
